version: 2.1
orbs:
  python: circleci/python@3.0.0
  node: circleci/node@7.0.0
  docker: circleci/docker@2.8.1

jobs:
  back-lint-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          name: Lint backend code (Python)
          working_directory: storm
          command: pylint storm/* --rcfile=.pylintrc
      - run:
          name: Run Django tests
          working_directory: storm
          command: python3 manage.py test

  front-lint:
    executor: node/default
    working_directory: storm-ui
    steps:
      - checkout
      - run:
          command: sudo npm install -g npm@latest
      - node/install-packages:
          override-ci-command: pnpm i
          pkg-manager: pnpm
      - run:
          name: Lint frontend code (React TS)
          command: pnpm lint

  deploy:
    executor: python/default
    steps:
      - run:
          name: Redeploy Backend API on Render
          command: |
            curl -X POST "https://api.render.com/deploy/srv-ctgr8gjgbbvc738um9v0?key=80u2Lsut3f8"
      - run:
          name: Redeploy Frontend on Render
          command: |
            curl -X POST "https://api.render.com/deploy/srv-ctgr3fij1k6c73a60ufg?key=UhLS7GPU0A0"

workflows:
  lint-test-and-deploy:
    jobs:
      - back-lint-and-test
      - front-lint
      - docker/publish: # build image & publish to Docker Hub
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          update-description: true
          dockerfile: Dockerfile
          requires:
            - back-lint-and-test
            - front-lint
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - docker/publish
          filters:
            branches:
              only: main # only deploy when on main
